name = "toolscout"
main = "worker.js"
compatibility_date = "2026-08-28"

[assets]
directory = "."
html_handling = "none"
not_found_handling = "404-page"
binding = "ASSETS"

[triggers]
crons = ["15 3 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "toolscout"
database_id = "cac6bc3c-d838-4edd-ba29-597030afb397"
migrations_dir = "migrations"
