import assert from 'node:assert/strict';
import fs from 'node:fs';
const supervisor=fs.readFileSync(new URL('../growth-supervisor.js',import.meta.url),'utf8');
const autonomous=fs.readFileSync(new URL('../distribution-autonomous-worker.js',import.meta.url),'utf8');
const network=fs.readFileSync(new URL('../distribution-network-worker.js',import.meta.url),'utf8');
const runtime=fs.readFileSync(new URL('../growth-runtime-closed-loop-worker.js',import.meta.url),'utf8');
const truth=fs.readFileSync(new URL('../operational-truth-reconciliation-worker.js',import.meta.url),'utf8');
assert.match(supervisor,/BACKLINK_ATTEMPT_MIN_24H=15/);
assert.match(supervisor,/BACKLINK_ATTEMPT_TARGET_24H=25/);
assert.match(supervisor,/BASELINE_EXTERNAL_EXECUTIONS_MIN_24H=15/);
assert.match(supervisor,/BASELINE_EXTERNAL_EXECUTIONS_TARGET_24H=25/);
assert.match(supervisor,/maximum_safe_always_on_acquisition/);
assert.match(supervisor,/wait_for_traffic_threshold:false/);
assert.doesNotMatch(supervisor,/else if\(strict24<=CRITICAL_STRICT_HUMANS_24H_MAX\)/);
assert.match(autonomous,/QUALIFY_LIMIT=48/);
assert.match(autonomous,/EXECUTION_LIMIT=24/);
assert.match(network,/MAX_CANDIDATES_PER_CYCLE=48/);
assert.match(network,/MAX_CONTACT_SCANS=16/);
assert.match(network,/MAX_ROUTE_ACTIONS_PER_CYCLE=32/);
assert.match(runtime,/AUTHORITY_ATTEMPT_MIN_24H=15/);
assert.match(runtime,/AUTHORITY_ATTEMPT_TARGET_24H=25/);
assert.match(runtime,/public-candidates\?limit=8/);
assert.match(truth,/AUTHORITY_POLICY_MIN_24H=15/);
assert.match(truth,/attemptTarget24h:AUTHORITY_POLICY_TARGET_24H/);
assert.match(truth,/canonicalAcquisitionSource:'ga4'/);
assert.match(truth,/strictHumanRole:'diagnostic_only'/);
assert.match(truth,/version:'business-truth-v6'/);
console.log('Acquisition surge core policy and Business Truth are aligned.');
