import assert from 'node:assert/strict';
import fs from 'node:fs';
const supervisor=fs.readFileSync(new URL('../growth-supervisor.js',import.meta.url),'utf8');
const autonomous=fs.readFileSync(new URL('../distribution-autonomous-worker.js',import.meta.url),'utf8');
const network=fs.readFileSync(new URL('../distribution-network-worker.js',import.meta.url),'utf8');
const throughput=fs.readFileSync(new URL('../distribution-throughput-worker.js',import.meta.url),'utf8');
const truth=fs.readFileSync(new URL('../operational-truth-reconciliation-worker.js',import.meta.url),'utf8');
assert.match(supervisor,/BACKLINK_ATTEMPT_MIN_24H=4/);
assert.match(supervisor,/BACKLINK_ATTEMPT_TARGET_24H=8/);
assert.match(supervisor,/BASELINE_EXTERNAL_EXECUTIONS_TARGET_24H=8/);
assert.match(supervisor,/BASELINE_EXTERNAL_EXECUTIONS_MAX_24H=12/);
assert.match(supervisor,/outcome_weighted_bounded_always_on/);
assert.match(supervisor,/activity_is_not_success:true/);
assert.match(supervisor,/existing_demand_search:60,authority_vendor_network:25,ai_aeo_discovery:10,growth_rnd:5/);
assert.match(autonomous,/QUALIFY_LIMIT=12/);
assert.match(autonomous,/EXECUTION_LIMIT=4/);
assert.match(network,/MAX_CANDIDATES_PER_CYCLE=16/);
assert.match(network,/MAX_CONTACT_SCANS=6/);
assert.match(network,/MAX_ROUTE_ACTIONS_PER_CYCLE=8/);
assert.match(throughput,/RESEARCH_BUDGET=8/);
assert.match(truth,/AUTHORITY_POLICY_MIN_24H=4/);
assert.match(truth,/ACQUISITION_SURGE_MAX_24H=12/);
assert.match(truth,/activityIsNotSuccess:true/);
assert.match(truth,/canonicalAcquisitionSource:'ga4'/);
console.log('Human Acquisition v4 policy and resource budgets are aligned.');
