import assert from 'node:assert/strict';
import fs from 'node:fs';
const src=fs.readFileSync(new URL('../audience-worker.js',import.meta.url),'utf8');
const wrangler=fs.readFileSync(new URL('../wrangler.toml',import.meta.url),'utf8');
assert.match(src,/const BLUESKY_MAX_GRAPHEMES=300;/);
assert.match(src,/const BLUESKY_REPLY_TARGET_GRAPHEMES=300;/);
assert.match(src,/new Intl\.Segmenter\('en',\{granularity:'grapheme'\}\)/);
assert.match(src,/dropped_trailing_sentence_to_limit/);
assert.match(src,/removed_dangling_sentence/);
assert.match(src,/reply_requires_regeneration/);
assert.match(src,/complete-or-block-no-synthetic-truncation-v2/);
assert.match(src,/BLUESKY_DANGLING_TERMINAL/);
assert.match(src,/BLUESKY_INTERNAL_CONTROL_EXACT/);
assert.match(src,/BLUESKY_MODEL_META_TEXT/);
assert.match(src,/reply_blocked_internal_control_text/);
assert.match(src,/public-facing-semantic-guard-v3/);
assert.match(src,/\/api\/audience\/bluesky-reply\/prepare/);
assert.match(src,/bluesky_reply_possible_hard_cut/);
assert.match(wrangler,/"\/api\/audience\/\*"/,'Bluesky reply preparation endpoint must route through the Worker');
assert.match(src,/replace\(\/\[\\u2013\\u2014\]\/g,'-'\)/,'ToolScout social copy must normalize em/en dashes');
console.log('Bluesky reply guard keeps replies complete, public-facing and inside platform limits.');
