import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {taskQualityIssues,partitionChairmanTasks,reconcileDuplicateSubmissionGates} from '../chairman-task-quality.js';
import {ensureHumanGateSchema,upsertHumanGate,markHumanGateOwnerComplete,resolveHumanGate} from '../human-gate-contract.js';
const db=new DatabaseSync(':memory:');
const env={DB:{prepare(sql){return {args:[],bind(...args){this.args=args;return this},async run(){const x=db.prepare(sql).run(...this.args);return {meta:{changes:Number(x.changes)}}},async first(){return db.prepare(sql).get(...this.args)||null},async all(){return {results:db.prepare(sql).all(...this.args)}}}},async batch(stmts){return Promise.all(stmts.map(x=>x.run()))}}};
const valid={engine:'distribution',id:'test',gate_key:'distribution:surface:test',action_url:'https://directory.example/submit',instructions:'Open https://directory.example/submit. Sign in and submit the prepared ToolScout profile once.',reason:'The submission page displays a password form that requires your account.',prepared_body:'ToolScout profile and description',expected_impact:'Unlock the directory listing.',estimated_minutes:5,after_action:'Verify the public listing and monitor referral traffic.',gate_evidence:{url:'https://directory.example/submit',checked_at:new Date().toISOString(),detail:'Password input observed.'}};
assert.deepEqual(taskQualityIssues(valid),[]);
for(const broken of [{instructions:'Human Gate Contract distribution:surface:test opened. Complete the exact external step from Chairman Queue.'},{action_url:'https://directory.example/api/submit'},{prepared_body:''},{reason:valid.instructions},{gate_evidence:{...valid.gate_evidence,checked_at:'2020-01-01'}}])assert.ok(taskQualityIssues({...valid,...broken}).length);
assert.equal(partitionChairmanTasks([valid,valid]).items.length,1);
assert.equal(partitionChairmanTasks([{...valid,instructions:''}]).quality_holds.length,1);
await ensureHumanGateSchema(env);
const input={engine:'distribution',subjectKey:'test',gateType:'authentication',reason:valid.reason,instructions:valid.instructions,actionUrl:valid.action_url,payload:{description:valid.prepared_body,gate_evidence:valid.gate_evidence}};
await assert.rejects(upsertHumanGate(env,{...input,instructions:'Human action required'}),/invalid_human_gate/);
const key=await upsertHumanGate(env,input);
assert.equal((await markHumanGateOwnerComplete(env,key)).ok,true);
await upsertHumanGate(env,{...input,reason:'A newer reason must not reopen a task that is awaiting verification.'});
assert.equal(db.prepare('SELECT status FROM human_gate_contract').get().status,'verification_pending');
await resolveHumanGate(env,key,{detail:'existing submission confirmed'});
await upsertHumanGate(env,input);
assert.equal(db.prepare('SELECT status FROM human_gate_contract').get().status,'resolved');
assert.equal((await markHumanGateOwnerComplete(env,key)).ok,false);
db.exec(`CREATE TABLE distribution_opportunities(surface_slug TEXT PRIMARY KEY,status TEXT,human_required INTEGER,action_url TEXT,live_url TEXT,next_action TEXT,updated_at TEXT);
CREATE TABLE distribution_contact_route_actions(opportunity_slug TEXT,surface_slug TEXT,execution_mode TEXT,status TEXT,last_result TEXT,next_action TEXT,updated_at TEXT);
CREATE TABLE distribution_submissions(surface_slug TEXT,status TEXT,human_required INTEGER,error TEXT,updated_at TEXT);
CREATE TABLE distribution_economic_learning(surface_slug TEXT,chairman_required INTEGER,updated_at TEXT);
CREATE TABLE distribution_events(event_id TEXT,surface_slug TEXT,event_type TEXT,status TEXT,source_url TEXT,destination_url TEXT,detail TEXT,observed_at TEXT,created_at TEXT);
INSERT INTO distribution_opportunities VALUES('launch-llama','pending_review',0,'https://tools.launchllama.co/products/toolscout',NULL,NULL,NULL),('test','auth_required',1,'https://tools.launchllama.co/submit',NULL,NULL,NULL);
INSERT INTO distribution_contact_route_actions VALUES('test','launch-llama','autonomous_qualification','auth_required',NULL,NULL,NULL);
UPDATE human_gate_contract SET status='open';`);
assert.equal((await reconcileDuplicateSubmissionGates(env)).reconciled,1);
assert.equal(db.prepare("SELECT status FROM distribution_opportunities WHERE surface_slug='launch-llama'").get().status,'pending_review');
assert.equal(db.prepare("SELECT status,human_required FROM distribution_opportunities WHERE surface_slug='test'").get().human_required,0);
assert.equal(db.prepare('SELECT status FROM human_gate_contract').get().status,'cancelled');
assert.equal(db.prepare('SELECT status FROM distribution_contact_route_actions').get().status,'exhausted');
assert.equal((await reconcileDuplicateSubmissionGates(env)).reconciled,0);
await upsertHumanGate(env,input);
assert.equal(db.prepare('SELECT status FROM human_gate_contract').get().status,'cancelled');
console.log('Chairman quality: invalid tasks withheld, state replay safe, Launch Llama reconciliation idempotent.');
