import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=path=>fs.readFileSync(new URL('../'+path,import.meta.url),'utf8');
const discoveryConfig=JSON.parse(read('data/distribution-discovery-sources.json'));
assert.ok(Number(discoveryConfig.guardrails?.max_fetches_per_run)<=6,'discovery must stay within the bounded source-fetch budget');
assert.ok(Number(discoveryConfig.guardrails?.max_candidates_per_source)<=30,'candidate fan-out must stay bounded');
const autonomousWorker=read('distribution-autonomous-worker.js');
assert.match(autonomousWorker,/const QUALIFY_LIMIT=24;/);
assert.match(autonomousWorker,/const EXECUTION_LIMIT=12;/);
assert.match(autonomousWorker,/const AUTHORITY_ATTEMPT_MIN_24H=4;/);
assert.match(autonomousWorker,/const AUTHORITY_ATTEMPT_TARGET_24H=50;/);
const network=read('distribution-network-worker.js');
assert.match(network,/const MAX_CANDIDATES_PER_CYCLE=16;/);
assert.match(network,/const MAX_CONTACT_SCANS=6;/);
assert.match(network,/const MAX_ROUTE_ACTIONS_PER_CYCLE=8;/);
const throughput=read('distribution-throughput-worker.js');
assert.match(throughput,/const RESEARCH_SCAN_LIMIT=120;/);
assert.match(throughput,/const RESEARCH_BUDGET=24;/);
assert.match(throughput,/const INDEXNOW_BATCH_LIMIT=25;/);
assert.match(throughput,/const VERIFY_LIMIT=80;/);
const supervisor=read('growth-supervisor.js');
assert.match(supervisor,/const MACHINE_SAFE_EXTERNAL_EXECUTIONS_MAX_24H=800;/);
const operationalTruth=read('operational-truth-reconciliation-worker.js');
assert.match(operationalTruth,/const MACHINE_SAFE_EXTERNAL_MAX_24H=800;/);
const orchestrator=read('distribution-orchestrator-worker.js');
const engineHealthSupervisor=orchestrator.indexOf("await run('supervisorAudit','growth','self_audit'");
const engineHealthPriorities=orchestrator.indexOf("await run('operatingPriorities','distribution','operating_priorities'");
assert.ok(engineHealthSupervisor>=0&&engineHealthPriorities>engineHealthSupervisor,'engine health must refresh supervisor before operating priorities');
assert.match(supervisor,/suppress_repetitive_routes_and_rotate_to_competitive_gap/);
assert.match(supervisor,/rank_by_human_referral_potential:true/);
const adapters=JSON.parse(read('data/distribution-submission-adapters.json'));
assert.equal(Number(adapters.policy?.max_automatic_per_run),12);
assert.equal(adapters.policy?.zero_cost_only,true);
assert.equal(adapters.policy?.scale_only_after_verified_human_or_commercial_evidence,true);
assert.ok(adapters.policy?.human_assisted_only?.includes('captcha'));
assert.ok(adapters.policy?.bootstrap_once_then_resume?.includes('account_creation'));
assert.ok(!adapters.policy?.never_automatic?.includes('captcha'));
assert.equal(adapters.policy?.human_gate_execution_policy,'non_blocking_sidecar_v2');
assert.equal(adapters.policy?.eligible_surface_policy,'execute_all_qualified_zero_cost_surfaces');
console.log('Distribution is outcome-weighted and bounded for continuous operation.');
