import assert from 'node:assert/strict';
import fs from 'node:fs';
const policy=JSON.parse(fs.readFileSync(new URL('../data/growth-rnd-policy.json',import.meta.url),'utf8'));
const playbook=JSON.parse(fs.readFileSync(new URL('../data/growth-acquisition-playbook.json',import.meta.url),'utf8'));
const frontier=JSON.parse(fs.readFileSync(new URL('../data/growth-rnd-frontier.json',import.meta.url),'utf8'));
const orchestrator=fs.readFileSync(new URL('../distribution-orchestrator-worker.js',import.meta.url),'utf8');
assert.equal(policy.frontierDiscovery.enabled,true);
assert.equal(policy.ideaDiscovery.enabled,true);
assert.equal(policy.resourcePolicy.netNewAcquisitionPlayDiscovery,true);
assert.equal(policy.resourcePolicy.maxNewExperimentsPerAudit,12);
assert.ok(frontier.ideas.length>=10);
assert.ok(playbook.plays.length>=8);
assert.match(orchestrator,/growth-rnd-frontier\.json/);
assert.match(orchestrator,/growth-acquisition-playbook\.json/);
assert.match(orchestrator,/growth_rnd_frontier/);
assert.match(orchestrator,/dynamic_surface_ideas/);
assert.match(orchestrator,/acquisition_plays_activated/);
assert.match(orchestrator,/bound_opportunities/);
assert.match(orchestrator,/new_actions_added/);
assert.match(orchestrator,/growthRndAuditDue\(env,12\)/);
console.log('Growth R&D preserves frontier ideation and adds automatic bounded acquisition-play execution.');
