import assert from 'node:assert/strict';
import fs from 'node:fs';
const src=fs.readFileSync(new URL('../growth-command-center-v2-worker.js',import.meta.url),'utf8');
assert.match(src,/BACKLINK_ATTEMPT_MIN_24H=4/);
assert.match(src,/BACKLINK_STAGNATION_HOURS=24/);
assert.match(src,/growth_rnd_frontier/);
assert.match(src,/rnd_frontier_count/);
assert.match(src,/Growth R&D frontier/);
assert.match(src,/New acquisition ideas not already implemented/);
assert.match(src,/semi-passive/);
console.log('Command Center exposes the net-new Growth R&D acquisition frontier.');
