import assert from 'node:assert/strict';
import fs from 'node:fs';
const policy=JSON.parse(fs.readFileSync(new URL('../data/growth-rnd-policy.json',import.meta.url),'utf8'));
const playbook=JSON.parse(fs.readFileSync(new URL('../data/growth-acquisition-playbook.json',import.meta.url),'utf8'));
const orchestrator=fs.readFileSync(new URL('../distribution-orchestrator-worker.js',import.meta.url),'utf8');
const commandCenter=fs.readFileSync(new URL('../growth-command-center-v2-worker.js',import.meta.url),'utf8');
assert.equal(policy.version,2);
assert.equal(policy.ideaDiscovery.enabled,true);
assert.equal(policy.resourcePolicy.netNewAcquisitionPlayDiscovery,true);
assert.equal(policy.resourcePolicy.noWaitForTrafficThreshold,true);
assert.ok(playbook.plays.length>=8);
assert.ok(playbook.plays.every(p=>p.steps.length>0));
assert.ok(playbook.plays.every(p=>p.steps.every(step=>policy.autonomousPrimitives.includes(step))));
assert.match(orchestrator,/growth-acquisition-playbook\.json/);
assert.match(orchestrator,/candidate_plays/);
assert.match(orchestrator,/bound_opportunities/);
assert.match(orchestrator,/new_actions_added/);
assert.match(orchestrator,/growthRndAuditDue\(env,12\)/);
assert.match(commandCenter,/serp_zero_click_capture/);
assert.match(commandCenter,/authority_publisher_outreach/);
assert.match(commandCenter,/vendor_distribution_flywheel/);
console.log('Growth R&D discovers and binds net-new automated acquisition plays.');
