import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {routeOwner,routeContract} from '../runtime-route-contract.js';

const read=p=>fs.readFileSync(new URL('../'+p,import.meta.url),'utf8');

test('route contract assigns one explicit owner to migrated control routes',()=>{
  assert.equal(routeOwner('/api/distribution/operating-decisions',{method:'GET'}).owner,'distribution_priority');
  assert.equal(routeOwner('/api/distribution/operating-decisions/rebalance',{method:'POST'}).owner,'distribution_priority');
  assert.equal(routeOwner('/api/engine-evidence',{method:'POST'}).owner,'mission_integrity');
  assert.equal(routeOwner('/api/compute/health',{method:'GET'}).owner,'compute_router');
  assert.equal(routeOwner('/api/seo/runtime-health',{method:'GET'}).owner,'seo_runtime');
  assert.equal(routeOwner('/api/distribution/authority/vetted-health',{method:'GET'}).owner,'authority_acquisition');
  assert.equal(routeOwner('/api/distribution/authority/closed-loop-health',{method:'GET'}).owner,'authority_health');
  assert.equal(routeOwner('/api/distribution/authority/close-loop',{method:'POST'}).owner,'growth_runtime_closed_loop');
  assert.ok(routeContract().earlyDispatchOwners.includes('growth_runtime_closed_loop'));
  assert.equal(routeOwner('/api/growth/supervisor/public',{method:'GET'}).owner,'distribution_orchestrator');
  assert.equal(routeOwner('/news/zapier-next-gen-zaps-mcp',{method:'GET'}).owner,'public_editorial_site');
  assert.equal(routeOwner('/software-trends-index',{method:'GET'}).owner,'public_editorial_site');
  assert.equal(routeOwner('/software-trends-index.json',{method:'GET'}).owner,'public_editorial_site');
  assert.equal(routeOwner('/mcp',{method:'POST'}).owner,'agent_protocol_core');
  assert.equal(routeOwner('/a2a',{method:'POST'}).owner,'agent_protocol_core');
  assert.equal(routeOwner('/.well-known/agent-card.json',{method:'GET'}).owner,'agent_protocol_core');
  assert.equal(routeOwner('/.well-known/toolscout-distribution.json',{method:'GET'}).owner,'machine_discovery_catalog');
  assert.equal(routeOwner('/.well-known/api-catalog',{method:'GET'}).owner,'machine_discovery_catalog');
  assert.equal(routeOwner('/api/distribution/priorities/public-reconcile',{method:'POST'}).owner,'distribution_orchestrator');
  assert.equal(routeOwner('/api/command-center-resilient-health',{method:'GET'}).owner,'command_center_resilient_health');
  assert.equal(routeOwner('/api/traffic-integrity-health',{method:'GET'}).owner,'traffic_integrity_health');
  assert.equal(routeOwner('/api/confirmed-visitor',{method:'POST'}).owner,'traffic_integrity_core');
  assert.equal(routeOwner('/api/confirmed-visitor',{method:'OPTIONS'}).owner,'traffic_integrity_core');
  assert.equal(routeOwner('/api/command-center-human-truth-chart-health',{method:'GET'}).owner,'human_truth_chart_health');
  assert.equal(routeOwner('/api/command-center-human-truth-details-health',{method:'GET'}).owner,'human_truth_details_health');
  assert.equal(routeOwner('/api/command-center-human-truth-final-health',{method:'GET'}).owner,'human_truth_final_health');
  assert.equal(routeOwner('/api/command-center-human-truth-health',{method:'GET'}).owner,'human_truth_base_health');
  assert.equal(routeOwner('/api/command-center-autoload-health',{method:'GET'}).owner,'command_center_autoload_health');
  assert.equal(routeOwner('/api/command-center-truth-health',{method:'GET'}).owner,'command_center_truth_health');
  assert.equal(routeOwner('/api/discovery-attribution-health',{method:'GET'}).owner,'discovery_attribution_health');
  assert.equal(routeOwner('/api/distribution/rss/status',{method:'GET'}).owner,'rss_distribution');
  assert.equal(routeOwner('/api/distribution/rss/publish',{method:'POST'}).owner,'rss_distribution');
  assert.equal(routeOwner('/api/stats',{method:'GET'}).owner,'admin_stats');
  assert.equal(routeOwner('/api/stats',{method:'POST'}).owner,'legacy_chain');
  assert.equal(routeOwner('/api/traffic-integrity-health',{method:'POST'}).owner,'legacy_chain');
  assert.equal(routeOwner('/analytics/api/chairman-queue',{method:'GET'}).owner,'analytics_chairman');
  assert.equal(routeOwner('/analytics/api/stats',{method:'GET'}).owner,'analytics_stats');
  assert.equal(routeOwner('/analytics/api/google/external-24h',{method:'GET'}).owner,'analytics_owner_exclusion');
  assert.equal(routeOwner('/analytics/api/google/acquisition-24h',{method:'GET'}).owner,'analytics_attribution_24h');
  assert.equal(routeOwner('/api/autonomous-growth-health',{method:'GET'}).owner,'d1_read_budget');
  assert.equal(routeOwner('/api/distribution/discovery-health',{method:'GET'}).owner,'d1_read_budget');
  assert.equal(routeOwner('/analytics/api/google/connect',{method:'GET'}).owner,'d1_read_budget');
  assert.equal(routeOwner('/analytics/api/google/disconnect',{method:'POST'}).owner,'d1_read_budget');
  assert.equal(routeOwner('/api/google-analytics/callback',{method:'GET'}).owner,'google_analytics_callback');
  assert.equal(routeOwner('/api/gsc-trend.svg',{method:'GET'}).owner,'gsc_trend_surface');
  assert.equal(routeOwner('/api/gsc-trend.css',{method:'GET'}).owner,'gsc_trend_surface');
  assert.equal(routeOwner('/api/health',{method:'GET'}).owner,'gsc_trend_surface');
  assert.equal(routeOwner('/sitemap.xml',{method:'GET'}).owner,'public_canonical_surface');
  assert.equal(routeOwner('/data/tools.json',{method:'GET'}).owner,'public_canonical_surface');
  assert.equal(routeOwner('/legacy-page.html',{method:'GET'}).owner,'public_canonical_surface');
  assert.equal(routeOwner('/analytics/api/human-actions',{method:'GET'}).owner,'analytics_human_actions');
  assert.equal(routeOwner('/analytics/api/human-actions/credential',{method:'POST'}).owner,'analytics_human_actions_mutation');
  assert.equal(routeOwner('/analytics/api/human-actions/gate',{method:'POST'}).owner,'analytics_human_actions_mutation');
  assert.equal(routeOwner('/analytics/api/human-actions/editorial',{method:'POST'}).owner,'analytics_human_actions_mutation');
  assert.equal(routeOwner('/api/command-center-business-truth/reconcile-affiliate-schema',{method:'POST'}).owner,'command_center_schema_control');
  assert.equal(routeOwner('/best-seo-tools-for-agencies',{method:'GET'}).owner,'public_decision');
  assert.equal(routeOwner('/tools/airtable',{method:'GET'}).owner,'public_decision');
  assert.equal(routeOwner('/tools/semrush',{method:'GET'}).owner,'public_decision');
  assert.equal(routeOwner('/tools/klaviyo',{method:'GET'}).owner,'public_decision');
  assert.equal(routeOwner('/tools/moz-pro',{method:'GET'}).owner,'public_decision');
  assert.equal(routeOwner('/tools/tally',{method:'GET'}).owner,'public_decision');
  assert.equal(routeOwner('/best-project-management-tools',{method:'GET'}).owner,'public_decision');
  assert.equal(routeOwner('/best-social-media-management-tools',{method:'GET'}).owner,'public_decision');
  assert.equal(routeOwner('/tools/typeform',{method:'GET'}).owner,'public_decision');
  assert.equal(routeOwner('/best-no-code-automation-tools',{method:'GET'}).owner,'public_decision');
  assert.equal(routeOwner('/tools',{method:'GET'}).owner,'public_navigation');
  assert.equal(routeOwner('/tools/',{method:'GET'}).owner,'public_navigation');
  assert.equal(routeOwner('/compare',{method:'GET'}).owner,'public_navigation');
  assert.equal(routeOwner('/guides',{method:'GET'}).owner,'public_navigation');
  assert.equal(routeOwner('/categories',{method:'GET'}).owner,'public_navigation');
  assert.equal(routeOwner('/crm-tools',{method:'GET'}).owner,'public_navigation');
  assert.equal(routeOwner('/seo-tools',{method:'GET'}).owner,'public_navigation');
  assert.equal(routeOwner('/blog/',{method:'GET'}).owner,'public_navigation');
  assert.equal(routeOwner('/blog',{method:'GET'}).owner,'legacy_chain');
  assert.equal(routeOwner('/blog/article',{method:'GET'}).owner,'legacy_chain');
  assert.equal(routeOwner('/go/airtable',{method:'GET'}).owner,'affiliate_redirect');
  assert.equal(routeOwner('/go/embed',{method:'GET'}).owner,'affiliate_redirect');
  assert.ok(routeContract().earlyDispatchOwners.includes('affiliate_redirect'));
  assert.equal(routeContract().invariant,'one_declared_owner_per_route_group');
});

test('unknown routes remain on the legacy fallback during staged migration',()=>{
  const route=routeOwner('/some-unmigrated-path',{method:'GET'});
  assert.equal(route.owner,'legacy_chain');
  assert.equal(route.plane,'legacy');
});

test('compute entrypoint early-dispatches only explicitly migrated owners',()=>{
  const src=read('compute-router-worker.js');
  const healthLanguage=read('command-center-health-language-worker.js');
  const adminStats=read('admin-stats-runtime.js');
  assert.match(src,/earlyOwnedRoute/);
  assert.match(src,/ownership\.owner==='distribution_priority'/);
  assert.match(src,/ownership\.owner==='distribution_orchestrator'/);
  assert.match(src,/ownership\.owner==='seo_runtime'/);
  assert.match(src,/ownership\.owner==='authority_acquisition'/);
  assert.match(src,/import base from '\.\/growth-command-center-v2-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/posthog-behavior-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/visitor-accuracy-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/visitor-dashboard-metrics-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/lemlist-profile-correction-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/discovery-attribution-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/discovery-attribution-health-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/command-center-truth-consolidation-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/command-center-autoload-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/command-center-resilient-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/command-center-human-truth-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/owner-exclusion-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/traffic-integrity-guard-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/traffic-integrity-live-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/outbound-integrity-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/visitor-integrity-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/traffic-integrity-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/command-center-human-truth-chart-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/command-center-human-truth-details-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/command-center-human-truth-final-worker\.js'/);
  assert.match(src,/transformTrafficIntegrityCoreResponse/);
  assert.doesNotMatch(src,/import base from '\.\/command-center-integrity-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/seo-cloudflare-runtime-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/authority-acquisition-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/ga4-owner-exclusion-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/ga4-attribution-24h-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/d1-read-budget-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/command-center-ga4-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/command-center-health-language-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/gsc-command-center-visible-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/gsc-command-center-trend-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/growth-runtime-authority-drain-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/growth-runtime-observability-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/growth-runtime-closed-loop-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/growth-runtime-integrity-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/command-center-light-theme-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/command-center-final-integrity-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/mission-integrity-v2-worker\.js'/);
  assert.doesNotMatch(src,/import base from '\.\/mission-integrity-worker\.js'/);
  assert.match(src,/handleMissionIntegrityRoute.*mission-integrity-v2-worker/);
  assert.match(src,/handleMissionIntegrityRoute/);
  assert.match(src,/handleGrowthClosedLoopRoute/);
  assert.match(src,/runGrowthClosedLoopScheduled/);
  assert.match(healthLanguage,/async function improveStats/);
  assert.match(healthLanguage,/url\.pathname==='\/analytics\/api\/stats'/);
  assert.match(healthLanguage,/url\.pathname==='\/api\/stats'/);
  assert.match(healthLanguage,/return improveStats\(response\)/);
  assert.match(adminStats,/legacyStatsBase\.fetch\(request,env,ctx\)/);
  assert.match(src,/applyMarkedOwnerAnalytics/);
  assert.match(src,/transformSeoPublicPage/);
  assert.match(src,/response=await transformSeoPublicPage\(request,response,env\)/);
  assert.match(src,/ownership\.owner==='mission_integrity'/);
  assert.match(src,/ownership\.owner==='growth_runtime_closed_loop'/);
  assert.match(src,/ownership\.owner==='public_editorial_site'/);
  assert.match(src,/ownership\.owner==='agent_protocol_core'/);
  assert.match(src,/ownership\.owner==='machine_discovery_catalog'/);
  assert.match(src,/ownership\.owner==='command_center_resilient_health'/);
  assert.match(src,/ownership\.owner==='command_center_schema_control'/);
  assert.match(src,/ownership\.owner==='traffic_integrity_health'/);
  assert.match(src,/ownership\.owner==='traffic_integrity_core'/);
  assert.match(src,/ownership\.owner==='human_truth_chart_health'/);
  assert.match(src,/ownership\.owner==='human_truth_details_health'/);
  assert.match(src,/ownership\.owner==='human_truth_final_health'/);
  assert.match(src,/ownership\.owner==='human_truth_base_health'/);
  assert.match(src,/ownership\.owner==='command_center_autoload_health'/);
  assert.match(src,/ownership\.owner==='command_center_truth_health'/);
  assert.match(src,/ownership\.owner==='discovery_attribution_health'/);
  assert.match(src,/ownership\.owner==='rss_distribution'/);
  assert.match(src,/handleRssDistributionRoute/);
  assert.match(src,/transformRssPublicResponse/);
  assert.match(src,/handleDiscoveryAttributionHealthRoute/);
  assert.match(src,/handleCommandCenterTruthHealthRoute/);
  assert.match(src,/handleCommandCenterAutoloadHealthRoute/);
  assert.match(src,/handleHumanTruthBaseRoute/);
  assert.match(src,/ownership\.owner==='admin_stats'/);
  assert.match(src,/ownership\.owner==='analytics_chairman'/);
  assert.match(src,/ownership\.owner==='analytics_stats'/);
  assert.match(src,/ownership\.owner==='analytics_owner_exclusion'/);
  assert.match(src,/ownership\.owner==='analytics_attribution_24h'/);
  assert.match(src,/ownership\.owner==='d1_read_budget'/);
  assert.match(src,/ownership\.owner==='google_analytics_callback'/);
  assert.match(src,/ownership\.owner==='gsc_trend_surface'/);
  assert.match(src,/ownership\.owner==='public_canonical_surface'/);
  assert.match(src,/handlePublicCanonicalSurfaceRoute/);
  assert.match(src,/transformPublicCanonicalResponse/);
  assert.match(src,/ownership\.owner==='analytics_human_actions'/);
  assert.match(src,/ownership\.owner==='analytics_human_actions_mutation'/);
  assert.match(src,/ownership\.owner==='public_decision'/);
  assert.match(src,/ownership\.owner==='public_navigation'/);
  assert.match(src,/X-ToolScout-Route-Owner/);
  assert.match(src,/\/api\/runtime\/route-contract/);
  assert.match(src,/\/api\/runtime\/route-owner/);
  assert.match(src,/return legacyFallback\(request,env,ctx\)/);
});

test('migrated route owners expose null-returning direct handlers',()=>{
  const priority=read('distribution-priority-worker.js');
  const orchestrator=read('distribution-orchestrator-worker.js');
  const seo=read('seo-cloudflare-runtime-worker.js');
  const authority=read('authority-acquisition-worker.js');
  const evidence=read('mission-integrity-v2-worker.js');
  const closedLoop=read('growth-runtime-closed-loop-worker.js');
  const analytics=read('command-center-resilient-worker.js');
  const affiliateRedirect=read('affiliate-redirect-runtime.js');
  const healthLanguage=read('command-center-health-language-worker.js');
  const adminStats=read('admin-stats-runtime.js');
  assert.match(priority,/export async function handleDistributionPriorityRoute/);
  assert.match(priority,/return null;/);
  assert.match(orchestrator,/export async function handleDistributionOrchestratorRoute/);
  assert.match(orchestrator,/return null;/);
  assert.match(seo,/export async function handleSeoRuntimeRoute/);
  assert.match(seo,/return null;/);
  assert.match(authority,/export async function handleAuthorityAcquisitionRoute/);
  assert.match(authority,/return null;/);
  assert.match(evidence,/export async function handleMissionIntegrityRoute/);
  assert.match(evidence,/return null;/);
  assert.match(closedLoop,/export async function handleGrowthClosedLoopRoute/);
  assert.match(closedLoop,/return null;/);
  assert.match(analytics,/export async function handleAnalyticsStatsReadRoute/);
  assert.match(analytics,/X-ToolScout-Read-Mode':'read-only/);
  assert.match(affiliateRedirect,/export async function handleAffiliateRedirectRoute/);
  assert.ok(affiliateRedirect.includes('distribution-embed-worker.js'));
  assert.doesNotMatch(affiliateRedirect,/CREATE TABLE|CREATE INDEX|ALTER TABLE/);
});

test('mission integrity runtime no longer creates schema',()=>{
  const evidence=read('mission-integrity-v2-worker.js');
  assert.doesNotMatch(evidence,/CREATE TABLE|CREATE INDEX/);
  assert.match(evidence,/mission_integrity_schema_not_migrated/);
});


test('Growth Planner runtime no longer creates schema',()=>{
  const planner=read('distribution-orchestrator-worker.js');
  assert.doesNotMatch(planner,/CREATE TABLE|CREATE INDEX|ALTER TABLE/);
  assert.match(planner,/growth_planner_schema_not_migrated/);
});


test('analytics read runtime uses migrated strict-human schema and no runtime DDL',()=>{
  const analytics=read('command-center-resilient-worker.js');
  assert.doesNotMatch(analytics,/CREATE TABLE|CREATE INDEX|ALTER TABLE/);
  assert.match(analytics,/strict_human_analytics_schema_not_migrated/);
});


test('catalog runtime schema is migration-owned, not request-owned',()=>{
  const catalog=read('catalog-autonomy-worker.js');
  assert.doesNotMatch(catalog,/CREATE TABLE|CREATE INDEX|ALTER TABLE/);
  assert.match(catalog,/catalog_runtime_schema_not_migrated/);
  const migration=read('migrations/0091_catalog_runtime_schema.sql');
  assert.match(migration,/CREATE TABLE IF NOT EXISTS catalog_runtime_state/);
  assert.match(migration,/CREATE TABLE IF NOT EXISTS catalog_runtime_candidates/);
  assert.match(migration,/CREATE TABLE IF NOT EXISTS catalog_quality_audit/);
});


test('human action mutation schemas are migration-owned',()=>{
  const auth=read('auth-automation.js');
  const gate=read('human-gate-contract.js');
  assert.doesNotMatch(auth,/CREATE TABLE|CREATE INDEX|ALTER TABLE/);
  assert.doesNotMatch(gate,/CREATE TABLE|CREATE INDEX|ALTER TABLE/);
  assert.match(auth,/auth_automation_schema_not_migrated/);
  assert.match(gate,/human_gate_schema_not_migrated/);
});


test('affiliate schema compatibility is migration-owned',()=>{
  const operational=read('command-center-business-truth-runtime.js');
  const owner=read('command-center-schema-control-runtime.js');
  assert.doesNotMatch(operational,/reconcileAffiliateNetworkEvidenceSchema/);
  assert.doesNotMatch(operational,/ALTER TABLE affiliate_network_click_evidence/);
  assert.doesNotMatch(owner,/CREATE TABLE|CREATE INDEX|ALTER TABLE|\.run\(|\.batch\(/);
  const migration=read('migrations/0097_affiliate_network_schema_completion.sql');
  assert.match(migration,/CREATE TABLE IF NOT EXISTS affiliate_network_accounts/);
  assert.match(migration,/CREATE TABLE IF NOT EXISTS affiliate_network_program_evidence/);
});
