INSERT INTO distribution_opportunities (
  surface_slug,
  surface_name,
  surface_type,
  audience_fit,
  authority,
  traffic_potential,
  backlink_value,
  acceptance_probability,
  automation_potential,
  effort_cost,
  distribution_score,
  status,
  action_url,
  human_required,
  next_action,
  last_checked_at,
  created_at,
  updated_at
) VALUES (
  'listed-startups',
  'Listed Startups',
  'agent_ready_startup_directory',
  83,
  60,
  62,
  75,
  95,
  95,
  10,
  80,
  'ready_to_submit',
  'https://listedstartups.com/api/listings',
  0,
  'REST publishing contract and ToolScout payload validated. Await explicit authorization to register an agent identity and obtain LISTED_STARTUPS_TOKEN before automatic publication.',
  datetime('now'),
  datetime('now'),
  datetime('now')
)
ON CONFLICT(surface_slug) DO UPDATE SET
  surface_name=excluded.surface_name,
  surface_type=excluded.surface_type,
  audience_fit=excluded.audience_fit,
  authority=excluded.authority,
  traffic_potential=excluded.traffic_potential,
  backlink_value=excluded.backlink_value,
  acceptance_probability=excluded.acceptance_probability,
  automation_potential=excluded.automation_potential,
  effort_cost=excluded.effort_cost,
  distribution_score=MAX(distribution_opportunities.distribution_score, excluded.distribution_score),
  status='ready_to_submit',
  action_url=excluded.action_url,
  human_required=0,
  next_action=excluded.next_action,
  last_checked_at=datetime('now'),
  updated_at=datetime('now');
