import fs from 'node:fs';
import path from 'node:path';

const ROOT=process.cwd();
const BASE='https://trytoolscout.org';
const EXCLUDE=/^(404|admin|analytics|click|google[0-9a-f]+|seo|tool|tools|compare)\.html$/i;
const CORE_PAGES=['guides.html','tools.html','compare.html','methodology.html','affiliate-disclosure.html','privacy.html','categories.html','crm-tools.html','seo-tools.html','software-trends-index.html','whats-new.html'];
const COMPARISON_RE=/^[a-z0-9-]+-vs-[a-z0-9-]+\.html$/i;
const baseIntents=JSON.parse(fs.readFileSync(path.join(ROOT,'data','intents.json'),'utf8'));
const longtailPath=path.join(ROOT,'data','seo-longtail.json');
const longtail=fs.existsSync(longtailPath)?JSON.parse(fs.readFileSync(longtailPath,'utf8')).intents||[]:[];
const consolidationsPath=path.join(ROOT,'data','seo-consolidations.json');
const consolidations=fs.existsSync(consolidationsPath)?JSON.parse(fs.readFileSync(consolidationsPath,'utf8')):{};
const intentSlugs=new Set([...baseIntents,...longtail].map(x=>x?.slug).filter(slug=>slug&&!consolidations[slug]));
const isIndexable=file=>{if(!fs.existsSync(file))return false;const html=fs.readFileSync(file,'utf8');return !/<meta[^>]+name=["']robots["'][^>]+content=["'][^"']*noindex/i.test(html)&&!/<meta[^>]+content=["'][^"']*noindex[^"']*["'][^>]+name=["']robots["']/i.test(html);};
const cleanFile=file=>String(file||'').replace(/\.html$/i,'');
const canonicalUrl=file=>{try{const html=fs.readFileSync(file,'utf8');const m=html.match(/<link[^>]+rel=["']canonical["'][^>]+href=["']([^"']+)["']/i)||html.match(/<link[^>]+href=["']([^"']+)["'][^>]+rel=["']canonical["']/i);return m?.[1]?.startsWith(BASE+'/')?m[1]:null}catch{return null}};
const publicUrl=file=>canonicalUrl(path.join(ROOT,file))||`${BASE}/${cleanFile(file)}`;
const urls=[BASE+'/',`${BASE}/guides`,...CORE_PAGES.filter(file=>fs.existsSync(path.join(ROOT,file))&&isIndexable(path.join(ROOT,file))).map(publicUrl)];
const blogIndex=path.join(ROOT,'blog','index.html');
if(isIndexable(blogIndex))urls.push(`${BASE}/blog/`);
const files=fs.readdirSync(ROOT).filter(name=>name.endsWith('.html')).filter(name=>!EXCLUDE.test(name)).filter(name=>name!=='index.html').filter(name=>intentSlugs.has(name.replace(/\.html$/i,''))||COMPARISON_RE.test(name)).filter(name=>isIndexable(path.join(ROOT,name))).sort();
for(const file of files)urls.push(canonicalUrl(path.join(ROOT,file))||publicUrl(file));
const blogDir=path.join(ROOT,'blog');
const blogFiles=fs.existsSync(blogDir)?fs.readdirSync(blogDir).filter(name=>name.endsWith('.html')&&name!=='index.html').filter(name=>isIndexable(path.join(blogDir,name))).sort():[];
for(const file of blogFiles)urls.push(canonicalUrl(path.join(blogDir,file))||`${BASE}/blog/${cleanFile(file)}`);
const newsDir=path.join(ROOT,'news');
const newsFiles=fs.existsSync(newsDir)?fs.readdirSync(newsDir).filter(name=>name.endsWith('.html')).filter(name=>isIndexable(path.join(newsDir,name))).sort():[];
for(const file of newsFiles)urls.push(canonicalUrl(path.join(newsDir,file))||`${BASE}/news/${cleanFile(file)}`);
const unique=[...new Set(urls)];
const toolDir=path.join(ROOT,'tools');
if(fs.existsSync(toolDir))for(const file of fs.readdirSync(toolDir).filter(name=>name.endsWith('.html')).filter(name=>isIndexable(path.join(toolDir,name))).sort())unique.push(canonicalUrl(path.join(toolDir,file))||`${BASE}/tools/${cleanFile(file)}`);
const finalUrls=[...new Set(unique)];
const xml=`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${finalUrls.map(u=>`  <url><loc>${u}</loc></url>`).join('\n')}\n</urlset>\n`;
fs.writeFileSync(path.join(ROOT,'sitemap.xml'),xml,'utf8');
console.log(JSON.stringify({urls:finalUrls.length,intentAndComparisonPages:files.length,indexableBlogPages:blogFiles.length,indexableNewsPages:newsFiles.length,blogIndexIncluded:finalUrls.includes(`${BASE}/blog/`),whatsNewIncluded:finalUrls.includes(`${BASE}/whats-new`),softwareTrendsIndexIncluded:finalUrls.includes(`${BASE}/software-trends-index`)}));
